query: chatgpt stars:>500 archived:false
root:
  categories:
    - title: Documentation and examples
      categories:
        - title: Lists, Guides and examples
          prompt: Documentation, lists, guides, or examples
        - title: Prompt engineering
          prompt: Information about prompt engineering
    - title: UIs
      categories:
        - title: Desktop applications
          prompt: General-purpose desktop ChatGPT client for regular users
        - title: Browser extensions
          prompt: General-purpose browser extension for ChatGPT for regular users
        - title: Web applications
          prompt: Web-based user ChatGPT interface for regular users
        - title: Messenger bots
          prompt: Messenger bots for ChatGPT for regular users
        - title: Mobile applications
          prompt: General-purpose mobile client for ChatGPT for regular users
        - title: CLI
          prompt: Command-line(shell) interface for ChatGPT for regular users
        - title: Other UIs
          prompt: Other user interfaces for ChatGPT for regular users
    - title: Integrations
      prompt: Addons, extensions, plug-ins for integrating LLM into  third-party applications
    - title: SDK, Libraries, Frameworks
      categories:
        - title: Python
          prompt: Python library, sdk or framework for developers not associated with any particular application
        - title: JavaScript/Typescript
          prompt: JavaScript or Typescript library, sdk or framework for developers not associated with any particular application
        - title: Golang
          prompt: Golang library, sdk or framework for developers not associated with any particular application
        - title: "C#"
          prompt: "C# library, sdk or framework for developers not associated with any particular application"
        - title: Swift
          prompt: Swift library, sdk or framework for developers not associated with any particular application
        - title: Kotlin
          prompt: Kotlin library, sdk or framework for developers not associated with any particular application
        - title: ChatGPT plugins
          prompt: ChatGPT plugins
        - title: Other sdk/libraries
          prompt: Other language library, sdk or framework for developers not associated with any particular application
    - title: ChatGPT-based applications
      prompt: ChatGPT-based applications for regular users that solve specialized problems rather than general tasks
    - title: Other
      prompt: Applications for other LLMs, other models and other not included in other categories
